<?php
/**
 * guardaremos diferentes datos relacionados con la web
 * meses, paises, datos de usuario, denuncias y privacidad
 *
 * @name datos.php
 * @author Iván Martínez Tutor
 */
/**
 * array psMeses
 * @funcionalidad contiene los datos en español de los meses
 */
$psMeses = [
    1 => "Enero",
    2 => "Febrero",
    3 => "Marzo",
    4 => "Abril",
    5 => "Mayo",
    6 => "Junio",
    7 => "Julio",
    8 => "Agosto",
    9 => "Septiembre",
    10 => "Octubre",
    11 => "Noviembre",
    12 => "Diciembre"
];

/**
 * psPrivacidad
 * @funcionalidad guardamos los datos de preferencia de privacidad del usuario
 */
$psPrivacidad = [
    "Nadie",
    "Usuarios que sigo y/o me siguen",
    "Mis seguidores",
    "Usuarios que sigo",
    "Usuarios que est&aacute;n registrados",
    "Todos los usuarios(visitantes tambi&eacute;n"
];

/**
 * psDenuncias
 * @funcionalidad guardamos los textos para los tipos de denuncia posibles
 * @var [type]
 */
$psDenuncias = [
    'users' => array(
        '',
        'Perfil falso.',
        'Usuario insultante y agresivo.',
        'Publicaciones inapropiadas.',
        'Foto de perfil inapropiada o de mal gusto.',
        'Publicidad no deseada (spam).',
    ),
    'posts' => array(
        '',
        'Re-Post',
        'Se hace spam.',
        'Los links no funcionan.',
        'Es racista o irrespetuoso.',
        'Contiene informaci&oacute;n personal.',
        'Es gore o asqueroso.',
        'Post demasiado pobre.',
        'No cumple con el protocolo.',
        'Otra raz&oacute;n (especificar)',
    ),
    'fotos' => array(
        '',
        'Ya est&aacute; publicada.',
        'Se hace Spam.',
        'La imagen no se ve.',
        'Es racista o irrespetuosa.',
        'Contiene informaci&oacute;n personal.',
        'Es gore o asquerosa.',
        'Otra raz&oacute;n (Especificar a continuaci&oacute;n)'
    ),
];

$psPerfilDatos = [
    'gustos' => array(
        'Hacer amigos.',
        'Conocer gente con mis intereses.',
        'Conocer gente para negocios.',
        'Encontrar pareja.',
        'Todas las anteriores.',
    ),
    'estado' => array(
        'Sin respuesta.',
        'Soltero/a',
        'Con novio/a',
        'Pareja de hecho',
        'Casado/a',
        'Empezando algo...',
    ),
    'hijos' => array(
        'Sin respuesta',
        'No tengo',
        'En un futuro',
        'No son lo m&iacute;o',
        'Tengo hijos',
    ),
    'vivo' => array(
        'Sin respuesta',
        'S&oacute;lo',
        'Con mis padres',
        'Con mi pareja',
        'Con mis amigos',
        'Otro',
    ),
    'pelo' => array(
        'Sin respuesta',
        'Negro',
        'Casta&ntilde;o oscuro',
        'Casta&ntilde;o claro',
        'Rubio',
        'Pelirrojo',
        'Gris',
        'Verde',
        'Naranja',
        'Morado',
        'Azul',
        'Canoso',
        'Te&ntilde;ido',
        'Rapado',
        'Calvo',
    ),
    'ojos' => array(
        'Sin respuesta',
        'Negros',
        'Marrones',
        'Azules',
        'Verdes',
        'Grises',
    ),
    'fisico' => array(
        'Sin respuesta',
        'Delgado/a',
        'Atl&eacute;tico/a',
        'Normal',
        'Algunos kilos de m&aacute;s',
        'Corpulento/a',
    ),
    'dieta' => array(
        'Sin respuesta',
        'Vegetariana',
        'Vegana',
        'De todo',
        'Comida basura',
    ),
    'tengo' => array(
        'Tatuajes',
        'Piercing',
    ),
    'fumo' => array(
        'Sin respuesta',
        'No',
        'Casualmente',
        'Socialmente',
        'Regularmente',
        'Mucho',
    ),
    'estudios' => array(
        'Sin respuesta',
        'Educaci&oacute; Secundaria Obligatoria',
        'Bachillerato',
        'FP Grado Medio',
        'FP Grado Superior',
        'Universitario',
        'Post Grado',
        'Master',
    ),
    'idiomas' => array(
        'Espa&ntilde;ol',
        'Ingl&eacute;s',
        'Franc&eacute;s',
        'Italiano',
        'Alem&aacute;n',
        'Otro',
    ),
    'inivel' => array(
        'Sin respuesta',
        'Sin conocimiento',
        'B&aacute;sico',
        'Intermedio',
        'Fluido',
        'Nativo',
    ),
    'ingresos' => array(
        'Sin respuesta',
        'Sin ingresos',
        'Ingresos bajos',
        'Ingresos medios',
        'Ingresos altos',
    ),
    'sector' => array(
        'Sin respuesta',
        'Actividades inmobiliarias',
        'Administraci&oacute;n',
        'Agricultura, ganader&iacute;a y pesca',
        'Agroalimentario',
        'Animaci&oacute;n',
        'Apuestas y casinos',
        'Arquitectura y planificaci&oacute;n',
        'Artes esc&eacute;nicas',
        'Artesan&iacute;a',
        'Art&iacute;culos de lujo y joyer&iacute;a',
        'Art&iacute;culos deportivos',
        'Atenci&oacute;n sanitaria y hospitalaria',
        'Audiovisual',
        'Automoci&oacute;n',
        'Banca',
        'Banca de inversiones',
        'Bellas artes',
        'Bibliotecas',
        'Biotecnolog&iacute;a',
        'Capital de riesgo y privado',
        'Construcci&oacute;n',
        'Consultor&iacute;a de estrategia y operaciones',
        'Cooperaci&oacute;n y desarrollo internacional',
        'Cosm&eacute;tica',
        'Cistal, cer&aacute;mica y hormig&oacute;n',
        'Departamento de defensa y del espacio exterior',
        'Deportes',
        'Desarrollo de programaci&oacute;n',
        'Dise&ntilde;o',
        'Dise&ntilde;o gr&aacute;fico',
        'Editorial',
        'Educaci&oacute;n',
        'El&eacute;ctrica',
        'Electr&oacute;nica de consumo',
        'Energ&iacute;a renovable y medio ambiente',
        'Entretenimiento',
        'Equipos inform&aacute;ticos',
        'Fotograf&iacute;a',
        'Gesti&oacute;n de inversiones',
        'Gran consumo y alimentaci&oacute;n',
        'Hosteler&iacute;a y restaurantes',
        'Importaci&oacute;n y exportaci&oacute;n',
        'Imprenta',
        'Industria aeroespacial y aviaci&oacute;n',
        'Industria farmace&uacute;tica',
        'Industria qu&iacute;mica',
        'Industria textil y moda',
        'Infraestructuras',
        'Ingenier&iacute;a',
        'Instalaciones y servicios recreativos',
        'Internet',
        'Investigaci&oacute;n',
        'Investigaci&oacute;n de mercado',
        'Log&iacute;stica',
        'Maquinaria',
        'Marketing y publicidad',
        'Material y equipo de negocios',
        'Medicina alternativa',
        'Medios de comunicaci&oacute;n offline',
        'Medios de comunicaci&oacute;n online',
        'Mercados de capital',
        'Miner&iacute;a y metalurgia',
        'Museos e instituciones',
        'M&uacute;sica',
        'Naval',
        'ONG y servicios sociales',
        'Petr&oacute;leo y energ&iacute;a',
        'Pl&aacute;stico, papel y madera',
        'Producci&oacute;n multimedia',
        'Programas inform&aacute;ticos',
        'Protecci&oacute;n civil',
        'Publicidad, RRPP y eventos',
        'Seguros',
        'Servicio de asesor&iacute;a y auditor&iacute;a',
        'Servicios de RRHH',
        'Servicios de seguridad',
        'Servicios financieros',
        'Servicios jur&iacute;dicos',
        'Servicios medioambientales',
        'Servicios y tecnolog&iacute;a de la informaci&oacute;n',
        'Cadena de suministro',
        'Tabacalera',
        'Telecomunicaciones',
        'Telemarketing',
        'Traducci&oacute;n',
        'Transporte y mensajeria',
        'Turismo',
        'Venta al por mayor',
        'Venta al por menor',
        'Veterinaria',
        'Videojuegos',
        'Salud, bienestar y fitness',
        'Otras actividades',
    ),
];
